general.import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 4, y = 4 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12.00
